<!-- Copyright 2026 上海如静知华信息科技有限公司 -->
<script setup>import AdminShell from '../../components/AdminShell.vue';import StatusBadge from '../../components/StatusBadge.vue';import {assets,workOrders,plans} from '../../api/mock';</script>
<template><AdminShell><template #title>能源驾驶舱</template>
 <div class="heading"><div><p>ENERGY & CARBON OVERVIEW</p><h1>能源运营驾驶舱</h1><span>聚合计量设备健康、节能任务负荷与运行成本，聚焦今日需要处理的事项</span></div><div><button class="btn ghost">下载晨会简报</button><button class="btn primary">＋ 新增计量点</button></div></div>
 <section class="kpis"><article><header>计量点总数 <i>▱</i></header><strong>1,248</strong><p>覆盖 6 个能源介质</p></article><article><header>数据在线率 <i>⌁</i></header><strong>96.8%</strong><p>较上月提升 0.6%</p></article><article class="attention"><header>开放任务 <i>▤</i></header><strong>37</strong><p><b>3</b> 单需今日响应</p></article><article><header>节能计划达成 <i>✓</i></header><strong>94.2%</strong><p>本月已完成 18 项</p></article></section>
 <div class="grid two"><section class="panel asset-health"><header><div><h2>计量点在线状态</h2><p>按关键计量设备健康评分统计</p></div><button>查看能耗分析 →</button></header><div class="health-composition"><div class="health-ring"><b>96.8%</b><small>数据在线率</small></div><div class="health-bars"><div><span>采集正常 <b>1,146 台</b></span><i><em style="width:92%"></em></i></div><div class="warn"><span>质量关注 <b>74 台</b></span><i><em style="width:58%"></em></i></div><div class="danger"><span>采集中断 <b>28 台</b></span><i><em style="width:22%"></em></i></div></div></div></section>
 <section class="panel maintenance-calendar"><header><div><h2>未来 7 天节能任务负荷</h2><p>计划保养与已排工单</p></div><em>7 月 31 日</em></header><div class="load-chart"><div v-for="(n,i) in [5,8,12,7,14,9,4]" :key="i"><b :style="{height:(n*8)+'px'}"></b><span>{{['四','五','六','日','一','二','三'][i]}}</span><small>{{n}}</small></div></div><footer><span><i></i>计划保养 38</span><span><i></i>节能任务 21</span></footer></section></div>
 <div class="grid lower"><section class="panel"><header><div><h2>重点区域能耗态势</h2><p>按健康风险与生产影响排序</p></div><button>计量点台账 →</button></header><div class="product-list"><article v-for="a in assets" :key="a.code"><div class="asset-icon">{{a.category.slice(0,1)}}</div><div><b>{{a.name}}</b><small>{{a.code}} · {{a.location}}</small></div><StatusBadge :value="a.health"/><div class="mini-progress"><span><i :style="{width:a.utilization+'%'}"></i></span><small>{{a.utilization}}%</small></div><em>{{a.custodian}}</em></article></div></section>
 <section class="panel"><header><div><h2>今日节能任务</h2><p>按优先级与承诺时间排列</p></div><button>工单中心 →</button></header><div class="change-list"><article v-for="w in workOrders.slice(0,3)" :key="w.no"><div><StatusBadge :value="w.priority"/><small>{{w.no}}</small></div><h3>{{w.title}}</h3><p>{{w.asset}} · {{w.type}} · {{w.assignee}}</p><footer><span>承诺 {{w.due}}</span><StatusBadge :value="w.status"/></footer></article></div></section>
 <section class="panel docs"><header><div><h2>近期能效计划</h2><p>未来两周到期项目</p></div><button>计划中心 →</button></header><div v-for="p in plans" :key="p.no" class="plan-row"><span class="plan-date">{{p.next}}</span><div><b>{{p.name}}</b><small>{{p.asset}} · {{p.team}}</small></div><StatusBadge :value="p.status"/></div></section></div>
 </AdminShell></template>
