/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. · https://www.zhuatech.cn/ */
package cn.zhuatech.ems.config;
import cn.zhuatech.ems.model.*; import cn.zhuatech.ems.repository.*; import org.springframework.boot.CommandLineRunner; import org.springframework.context.annotation.*; import org.springframework.security.crypto.password.PasswordEncoder; import java.math.BigDecimal; import java.time.*;
@Configuration public class DataInitializer {
    @Bean CommandLineRunner seed(UserRepository users,AssetRepository assets,SparePartRepository parts,MaintenancePlanRepository plans,WorkOrderRepository orders,InspectionRecordRepository inspections,PasswordEncoder encoder){return args->{if(users.count()>0)return;
        users.save(new UserAccount("admin",encoder.encode("admin123"),"资产平台主管",UserAccount.Role.ADMIN)); users.save(new UserAccount("asset",encoder.encode("asset123"),"资产管理员",UserAccount.Role.ASSET_MANAGER)); users.save(new UserAccount("technician",encoder.encode("tech123"),"节能巡检员",UserAccount.Role.TECHNICIAN));
        assets.save(new Asset("AST-CNC-018","五轴加工中心","生产计量设备","一号工厂·精加工区","许亦",new BigDecimal("2860000"),LocalDate.of(2022,4,18),"健康","运行中")); assets.save(new Asset("AST-AHU-006","组合式空调机组","动力计量设备","一号工厂·屋顶机房","陈序",new BigDecimal("480000"),LocalDate.of(2021,9,8),"需关注","运行中")); assets.save(new Asset("AST-CMP-012","变频螺杆空压机","动力计量设备","公用工程站","梁川",new BigDecimal("635000"),LocalDate.of(2023,2,14),"健康","运行中")); assets.save(new Asset("AST-AGV-027","潜伏式搬运机器人","物流计量设备","成品仓·A 区","周岚",new BigDecimal("168000"),LocalDate.of(2024,6,20),"需关注","停机检修"));
        parts.save(new SparePart("SP-BRG-6208","主轴精密轴承","6208/P4","套",3,4,"计量设备备件库")); parts.save(new SparePart("SP-FLT-AHU6","初效过滤器","G4 595×595","片",18,12,"公用工程库")); parts.save(new SparePart("SP-OIL-CMP46","空压机润滑油","ISO VG46 / 20L","桶",5,3,"计量设备备件库")); parts.save(new SparePart("SP-WHL-AGV27","AGV 驱动轮","PU 180mm","件",1,2,"物流备件库"));
        plans.save(new MaintenancePlan("MP-CNC-018-M","AST-CNC-018","加工中心月度点检",30,LocalDate.now().plusDays(2),"精密节能组","生效中")); plans.save(new MaintenancePlan("MP-AHU-006-Q","AST-AHU-006","空调机组季度保养",90,LocalDate.now().plusDays(5),"公用工程组","生效中")); plans.save(new MaintenancePlan("MP-CMP-012-M","AST-CMP-012","空压机运行保养",45,LocalDate.now().plusDays(9),"动力节能组","生效中"));
        orders.save(new WorkOrder("WO-20260731-014","AST-AGV-027","驱动轮异响并伴随定位偏差","异常节能","特急","宋启",LocalDateTime.now().plusHours(4),"处理中")); orders.save(new WorkOrder("WO-20260731-009","AST-AHU-006","送风压差持续高于预警线","状态节能","紧急","陈序",LocalDateTime.now().plusHours(8),"待接单")); orders.save(new WorkOrder("WO-20260730-026","AST-CNC-018","主轴振动趋势复核与润滑检查","预防保养","一般","许亦",LocalDateTime.now().plusDays(2),"待验收")); orders.save(new WorkOrder("WO-20260729-018","AST-CMP-012","更换油分芯并复位保养计时","计划保养","一般","梁川",LocalDateTime.now().minusDays(1),"已完成"));
        inspections.save(new InspectionRecord("IR-20260731-031","AST-AGV-027","周岚",LocalDateTime.now().minusHours(2),"异常","右侧驱动轮温升 18℃，建议立即停机检查")); inspections.save(new InspectionRecord("IR-20260731-025","AST-CNC-018","许亦",LocalDateTime.now().minusHours(4),"正常","主轴、刀库与冷却系统运行正常")); inspections.save(new InspectionRecord("IR-20260730-086","AST-AHU-006","陈序",LocalDateTime.now().minusDays(1),"异常","初效段压差 182Pa，接近更换阈值")); inspections.save(new InspectionRecord("IR-20260730-071","AST-CMP-012","梁川",LocalDateTime.now().minusDays(1),"正常","排气温度与加载电流在控制范围内"));
    };}
}
