/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. · https://www.zhuatech.cn/ */
package cn.zhuatech.ems;
import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.test.web.servlet.MockMvc; import java.time.LocalDateTime; import java.util.regex.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc class EmsApiIntegrationTests {
    @Autowired MockMvc mvc;
    private String login() throws Exception {String json=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\"admin\",\"password\":\"admin123\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.user.role").value("ADMIN")).andReturn().getResponse().getContentAsString();Matcher m=Pattern.compile("\\\"token\\\":\\\"([^\\\"]+)\\\"").matcher(json);if(!m.find())throw new AssertionError("登录响应中缺少 token");return m.group(1);}
    @Test void adminCanReadDashboardAndAssets() throws Exception {String token=login();mvc.perform(get("/api/ems/dashboard").header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$.data.assetCount").value(4)).andExpect(jsonPath("$.data.openOrders").value(3));mvc.perform(get("/api/ems/assets").header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$.data.length()").value(4));}
    @Test void assetManagerCanCreateWorkOrder() throws Exception {String due=LocalDateTime.now().plusDays(2).withNano(0).toString();String body="{\"assetCode\":\"AST-CNC-018\",\"title\":\"测试节能任务\",\"orderType\":\"异常节能\",\"priority\":\"一般\",\"assignee\":\"测试员\",\"dueAt\":\""+due+"\"}";mvc.perform(post("/api/ems/work-orders").header("Authorization","Bearer "+login()).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("待接单"));}
    @Test void adminCanAnalyzeCriticalEnergyAnomaly() throws Exception {mvc.perform(post("/api/ems/energy-anomaly").header("Authorization","Bearer "+login()).contentType(MediaType.APPLICATION_JSON).content("{\"meterName\":\"厂区总表\",\"currentKwh\":15000,\"baselineKwh\":10000,\"productionChangePercent\":10,\"tariff\":0.8,\"carbonFactor\":0.57,\"alertThresholdPercent\":15}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.expectedKwh").value(11000)).andExpect(jsonPath("$.data.excessKwh").value(4000)).andExpect(jsonPath("$.data.deviationPercent").value(36.36)).andExpect(jsonPath("$.data.excessCost").value(3200)).andExpect(jsonPath("$.data.excessCarbonKg").value(2280)).andExpect(jsonPath("$.data.status").value("CRITICAL"));}
    @Test void anonymousRequestIsDenied() throws Exception {mvc.perform(get("/api/ems/assets")).andExpect(status().isForbidden());}
}
