/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. */
package cn.zhuatech.ems.dto;
import cn.zhuatech.ems.model.*; import jakarta.validation.constraints.*; import java.math.BigDecimal; import java.time.*; import java.util.List;
public final class EmsDto {
    private EmsDto(){}
    public record AssetView(Long id,String assetCode,String assetName,String category,String location,String custodian,BigDecimal originalValue,LocalDate commissionedOn,String healthStatus,String operationStatus){public static AssetView from(Asset a){return new AssetView(a.getId(),a.getAssetCode(),a.getAssetName(),a.getCategory(),a.getLocation(),a.getCustodian(),a.getOriginalValue(),a.getCommissionedOn(),a.getHealthStatus(),a.getOperationStatus());}}
    public record SparePartView(Long id,String partCode,String partName,String specification,String unit,Integer stockQuantity,Integer safetyStock,String warehouse,boolean belowSafetyStock){public static SparePartView from(SparePart p){return new SparePartView(p.getId(),p.getPartCode(),p.getPartName(),p.getSpecification(),p.getUnit(),p.getStockQuantity(),p.getSafetyStock(),p.getWarehouse(),p.isBelowSafetyStock());}}
    public record PlanView(Long id,String planNo,String assetCode,String planName,Integer cycleDays,LocalDate nextExecutionDate,String team,String status){public static PlanView from(MaintenancePlan p){return new PlanView(p.getId(),p.getPlanNo(),p.getAssetCode(),p.getPlanName(),p.getCycleDays(),p.getNextExecutionDate(),p.getTems(),p.getStatus());}}
    public record WorkOrderView(Long id,String orderNo,String assetCode,String title,String orderType,String priority,String assignee,LocalDateTime dueAt,String status){public static WorkOrderView from(WorkOrder w){return new WorkOrderView(w.getId(),w.getOrderNo(),w.getAssetCode(),w.getTitle(),w.getOrderType(),w.getPriority(),w.getAssignee(),w.getDueAt(),w.getStatus());}}
    public record InspectionView(Long id,String recordNo,String assetCode,String inspector,LocalDateTime inspectedAt,String result,String finding){public static InspectionView from(InspectionRecord i){return new InspectionView(i.getId(),i.getRecordNo(),i.getAssetCode(),i.getInspector(),i.getInspectedAt(),i.getResult(),i.getFinding());}}
    public record Dashboard(long assetCount,long attentionAssets,long openOrders,long urgentOrders,long upcomingPlans,long abnormalInspections,List<AssetView> keyAssets,List<WorkOrderView> urgentWorkOrders,List<PlanView> upcomingMaintenance){}
    public record CreateAssetRequest(@NotBlank String assetCode,@NotBlank String assetName,@NotBlank String category,@NotBlank String location,@NotBlank String custodian,@NotNull @PositiveOrZero BigDecimal originalValue,@NotNull @PastOrPresent LocalDate commissionedOn){}
    public record CreateWorkOrderRequest(@NotBlank String assetCode,@NotBlank @Size(max=140) String title,@NotBlank String orderType,@Pattern(regexp="一般|紧急|特急") String priority,@NotBlank String assignee,@NotNull @FutureOrPresent LocalDateTime dueAt){}
}
